name: CI
on:
  push:
  pull_request:
  workflow_dispatch: {}

env:
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          profile: minimal
      # Smart caching for Rust projects.
      # Includes workaround for macos cache corruption.
      # - https://github.com/rust-lang/cargo/issues/8603
      # - https://github.com/actions/cache/issues/403
      - uses: Swatinem/rust-cache@v2
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: create kubernetes cluster
        run: |
          scripts/kind.sh
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
